name: Release WordPress Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  PLUGIN_SLUG: ${{ github.event.repository.name }}

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Get Plugin Version
        id: get_version
        run: |
          VERSION=$(grep -m 1 "Version:" ${{ env.PLUGIN_SLUG }}.php | awk '{print $NF}' | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Build plugin
        run: |
          # PHP
          composer install --no-dev --optimize-autoloader

          # Javascript and CSS
          npm install
          npm run build

      - name: Prepare Plugin for Zipping
        run: |
          mkdir -p ${{ env.PLUGIN_SLUG }}

          # Copy your specific architecture folders
          cp -r admin ${{ env.PLUGIN_SLUG }}/
          rm -rf ${{ env.PLUGIN_SLUG }}/admin/src
          cp -r vendor ${{ env.PLUGIN_SLUG }}/
          cp ${{ env.PLUGIN_SLUG }}.php ${{ env.PLUGIN_SLUG }}/
          cp uninstall.php ${{ env.PLUGIN_SLUG }}/
          cp README.md ${{ env.PLUGIN_SLUG }}/
          cp LICENSE ${{ env.PLUGIN_SLUG }}/

      - name: Create Zip Archive
        run: |
          zip -r ${{ env.PLUGIN_SLUG }}-${{ env.VERSION }}.zip ${{ env.PLUGIN_SLUG }}/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PLUGIN_SLUG }}-v${{ env.VERSION }}
          path: ${{ env.PLUGIN_SLUG }}-${{ env.VERSION }}.zip
          retention-days: 7

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view v${{ env.VERSION }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Release v${{ env.VERSION }} already exists. Skipping..."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: ${{ env.PLUGIN_SLUG }}-${{ env.VERSION }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
